server:
  port: 8081

spring:
  application:
    name: taxi-service-api
  datasource:
    url: jdbc:h2:mem:demodb;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    create-schemas: true
    default-schema: PUBLIC
